"use client";

import { useState, useTransition } from "react";
import { useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/ui-kit";
import { startAdminImpersonation } from "../actions";

type Row = Record<string, unknown>;
export function AccessView({ users, customers, risks, canImpersonate }: { users: Row[]; customers: Row[]; risks: Row[]; canImpersonate: boolean }) { const t = useTranslations("admin"); const [mode, setMode] = useState("ROLE_PREVIEW"); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition(); function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); form.set("mode", mode); startTransition(() => { void startAdminImpersonation(form).then(() => setMessage(t("previewBanner", { role: mode === "ROLE_PREVIEW" ? t("role") : t("vendorImpersonation") }))).catch((error: unknown) => setMessage(error instanceof Error ? error.message : t("error"))); }); } return <div className="space-y-6"><PageHeader title={mode === "ROLE_PREVIEW" ? t("previewRole") : t("vendorImpersonation")} description={t("impersonationBanner")} /><div className="flex gap-2"><Button type="button" variant={mode === "ROLE_PREVIEW" ? "default" : "outline"} onClick={() => setMode("ROLE_PREVIEW")}>{t("previewRole")}</Button><Button type="button" variant={mode === "VENDOR_IMPERSONATION" ? "default" : "outline"} onClick={() => setMode("VENDOR_IMPERSONATION")}>{t("vendorImpersonation")}</Button></div>{canImpersonate ? <form onSubmit={submit} className="space-y-4 rounded-lg bg-slate-50 p-4">{mode === "ROLE_PREVIEW" ? <label className="block text-sm font-medium text-primary">{t("usersTitle")}<select name="targetUserId" required className="mt-1 min-h-11 w-full rounded-md border border-slate-300 bg-white px-2">{users.map((user) => <option key={String(user.id)} value={String(user.id)}>{String(user.full_name)} · {String((user.role as Row | null)?.name ?? user.role_id)}</option>)}</select></label> : <label className="block text-sm font-medium text-primary">{t("customer")}<select name="targetCustomerId" required className="mt-1 min-h-11 w-full rounded-md border border-slate-300 bg-white px-2">{customers.map((customer) => <option key={String(customer.id)} value={String(customer.id)}>{String(customer.business_name)}</option>)}</select></label>}<p className="text-sm text-muted-foreground">{t("impersonationBanner")}</p><Button type="submit" disabled={pending}>{t("startPreview")}</Button></form> : null}<section className="space-y-3 rounded-lg border border-slate-200 bg-white p-4"><h2 className="font-semibold text-primary">{t("accessAudit")}</h2>{risks.length ? risks.map((risk, index) => <div key={`${String(risk.risk_type)}-${index}`} className="rounded-md border border-[#b42318] p-3 text-sm"><p className="font-semibold text-primary">{String(risk.risk_type)} · {String(risk.severity)}</p><p className="text-muted-foreground"><bdi>{String(risk.subject)}</bdi> — {String(risk.detail)}</p></div>) : <p className="text-muted-foreground">{t("noAnomalies")}</p>}</section>{message ? <p role="status" className="text-sm font-medium text-primary">{message}</p> : null}</div>; }
