"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState, PageHeader } from "@/components/ui-kit";
import { bounceRecoveryCheque, clearRecoveryCheque, verifyRecoveryDeposit } from "@/app/[locale]/(sales)/sales/recovery/actions";

type AdminRecoveryData = { ageing: Array<Record<string, unknown>>; progress: Array<Record<string, unknown>>; deposits: Array<Record<string, unknown>>; bounced: Array<Record<string, unknown>>; depositedCheques: Array<Record<string, unknown>>; overdue: Array<Record<string, unknown>> };

export function AdminRecoveryView({ data }: Readonly<{ data: AdminRecoveryData }>) {
  const t = useTranslations("recovery");
  const [message, setMessage] = useState<string | null>(null);
  async function verify(formData: FormData) { await verifyRecoveryDeposit(formData); setMessage(t("verified")); }
  async function clear(formData: FormData) { await clearRecoveryCheque(formData); setMessage(t("cleared")); }
  async function bounce(formData: FormData) { await bounceRecoveryCheque(formData); setMessage(t("bounced")); }
  return <div className="space-y-6"><PageHeader title={t("adminRecoveryTitle")} description={t("adminRecoveryDescription")} />{message ? <p role="status" className="rounded-md bg-slate-100 p-3 text-sm">{message}</p> : null}
    <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>{t("ageing")}</CardTitle></CardHeader><CardContent className="space-y-2">{data.ageing.length ? data.ageing.map((row, index) => <div key={index} className="flex justify-between border-b border-slate-100 py-2"><span>{String(row.bucket ?? row.ageing_bucket ?? "")}</span><bdi>{String(row.receivable_pkr ?? row.amount_pkr ?? "0.00")}</bdi></div>) : <EmptyState title={t("noCustomers")} />}</CardContent></Card>
      <Card><CardHeader><CardTitle>{t("recoveryProgress")}</CardTitle></CardHeader><CardContent className="space-y-2">{data.progress.length ? data.progress.map((row, index) => <div key={index} className="rounded-md border border-slate-200 p-3"><p className="font-semibold">{String(row.agent_name ?? row.agent_code ?? "")}</p><p className="text-sm text-slate-600">{t("recovered")}: <bdi>{String(row.recovered_amount_pkr ?? "0.00")}</bdi> · {t("target")}: <bdi>{String(row.target_amount_pkr ?? "0.00")}</bdi></p></div>) : <EmptyState title={t("noCustomers")} />}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>{t("pendingDeposits")}</CardTitle></CardHeader><CardContent className="space-y-3">{data.deposits.length ? data.deposits.map((row, index) => <div key={index} className="rounded-md border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><span>{String(row.agent_name ?? row.agent_code ?? "")}</span><bdi>{String(row.total_amount_pkr ?? "0.00")}</bdi></div><div className="mt-3 flex flex-wrap gap-2"><form action={verify}><input type="hidden" name="depositId" value={String(row.deposit_id ?? row.id ?? "")} /><input type="hidden" name="status" value="VERIFIED" /><Button type="submit">{t("verify")}</Button></form><form action={verify}><input type="hidden" name="depositId" value={String(row.deposit_id ?? row.id ?? "")} /><input type="hidden" name="status" value="DISPUTED" /><input name="note" required placeholder={t("verificationNote")} className="rounded-md border border-slate-300 px-3" /><Button type="submit" variant="outline">{t("dispute")}</Button></form></div></div>) : <EmptyState title={t("noCollectedPayments")} />}</CardContent></Card>
    <Card><CardHeader><CardTitle>{t("clearCheque")}</CardTitle></CardHeader><CardContent className="space-y-3">{data.depositedCheques.length ? data.depositedCheques.map((row, index) => <div key={index} className="rounded-md border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><span>{String(row.business_name ?? "")}</span><bdi>{String(row.amount_pkr ?? "0.00")}</bdi></div><p className="text-sm text-slate-600">{String(row.cheque_number ?? "")} · {String(row.bank_name ?? "")}</p><div className="mt-3 flex flex-wrap gap-2"><form action={clear}><input type="hidden" name="collectionId" value={String(row.collection_id ?? "")} /><Button type="submit">{t("clearCheque")}</Button></form><form action={bounce}><input type="hidden" name="collectionId" value={String(row.collection_id ?? "")} /><input required name="reason" placeholder={t("reason")} className="rounded-md border border-slate-300 px-3" /><Button type="submit" variant="destructive">{t("bounceCheque")}</Button></form></div></div>) : <EmptyState title={t("noCollectedPayments")} />}</CardContent></Card>
    <Card><CardHeader><CardTitle>{t("bouncedCheques")}</CardTitle></CardHeader><CardContent className="space-y-3">{data.bounced.length ? data.bounced.map((row, index) => <div key={index} className="rounded-md border border-slate-200 p-4"><p className="font-semibold">{String(row.business_name ?? "")}</p><p className="text-sm"><bdi>{String(row.amount_pkr ?? "0.00")}</bdi> · {String(row.receipt_number ?? "")}</p></div>) : <EmptyState title={t("noCollectedPayments")} />}</CardContent></Card>
    <Card><CardHeader><CardTitle>{t("topOverdue")}</CardTitle></CardHeader><CardContent className="space-y-3">{data.overdue.length ? data.overdue.map((row, index) => <div key={index} className="rounded-md border border-slate-200 p-4"><div className="flex justify-between gap-3"><span>{String(row.business_name ?? "")}</span><bdi>{String(row.balance_pkr ?? "0.00")}</bdi></div><p className="text-sm text-slate-600">{t("daysOverdue")}: <bdi>{String(row.days_overdue ?? "0")}</bdi></p>{row.cheque_id ? <div className="mt-2 flex gap-2"><form action={clear}><input type="hidden" name="collectionId" value={String(row.cheque_id)} /><Button type="submit" variant="outline">{t("clearCheque")}</Button></form><form action={bounce}><input type="hidden" name="collectionId" value={String(row.cheque_id)} /><input required name="reason" placeholder={t("reason")} className="rounded-md border border-slate-300 px-3" /><Button type="submit" variant="destructive">{t("bounceCheque")}</Button></form></div> : null}</div>) : <EmptyState title={t("noCustomers")} />}</CardContent></Card>
  </div>;
}
