"use client";

import { useState, useTransition } from "react";
import { useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";
import { EmptyState, PageHeader } from "@/components/ui-kit";
import { recordAdminLedgerPayment } from "../actions";

type Row = Record<string, unknown>;
export function AdminRecordList({ kind, rows, query }: { kind: "orders" | "quotes"; rows: Row[]; query: { search?: string; status?: string } }) { const t = useTranslations("admin"); const title = kind === "orders" ? t("ordersTitle") : t("quotesTitle"); const description = kind === "orders" ? t("ordersDescription") : t("quotesDescription"); const keys = kind === "orders" ? ["order_number", "status", "total_pkr", "placed_at", "placed_via"] : ["quote_number", "status", "valid_until", "created_at", "responded_at"]; return <div className="space-y-6"><PageHeader title={title} description={description} /><Filter query={query} /><Table rows={rows} keys={keys} /><>{rows.length === 0 ? <EmptyState title={t("noDashboardData")} description={t("noDashboardDataHint")} /> : null}</></div>; }
function Filter({ query }: { query: { search?: string; status?: string } }) { const t = useTranslations("admin"); return <form method="get" className="flex flex-col gap-3 rounded-lg bg-slate-50 p-4 sm:flex-row"><label className="flex-1 text-sm font-medium text-primary">{t("search")}<input name="search" defaultValue={query.search ?? ""} className="mt-1 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3" /></label><label className="text-sm font-medium text-primary">{t("status")}<select name="status" defaultValue={query.status ?? ""} className="mt-1 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3"><option value="">{t("allStatuses")}</option>{["DRAFT","PENDING_APPROVAL","PLACED","CONFIRMED","PICKED","DISPATCHED","DELIVERED","CANCELLED","REQUESTED","IN_REVIEW","QUOTED","ACCEPTED","REJECTED","EXPIRED","CONVERTED"].map((value) => <option key={value} value={value}>{value}</option>)}</select></label><Button type="submit" className="min-h-11 self-end">{t("search")}</Button></form>; }
function Table({ rows, keys }: { rows: Row[]; keys: string[] }) { return rows.length ? <div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="min-w-[720px] w-full text-sm"><thead className="bg-slate-50"><tr>{keys.map((key) => <th key={key} className="p-3 text-start">{key}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id ?? index)} className="border-t border-slate-200">{keys.map((key) => <td key={key} className="p-3"><bdi>{String(row[key] ?? "—")}</bdi></td>)}</tr>)}</tbody></table></div> : null; }

export function TeamView({ metrics, progress }: { metrics: Row[]; progress: Row[] }) { const t = useTranslations("admin"); return <div className="space-y-6"><PageHeader title={t("salesTeamTitle")} description={t("salesTeamDescription")} />{metrics.length === 0 ? <EmptyState title={t("noTeam")} description={t("noDashboardDataHint")} /> : <div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="min-w-[1000px] w-full text-sm"><thead className="bg-slate-50"><tr>{["agent_name", "orders_count", "revenue_pkr", "activities_count", "quote_conversion_rate", "target_progress_percent", "visit_flags_count"].map((key) => <th key={key} className="p-3 text-start">{key}</th>)}</tr></thead><tbody>{metrics.map((row, index) => <tr key={String(row.agent_id ?? index)} className="border-t border-slate-200">{["agent_name", "orders_count", "revenue_pkr", "activities_count", "quote_conversion_rate", "target_progress_percent", "visit_flags_count"].map((key) => <td key={key} className="p-3"><bdi>{String(row[key] ?? "—")}</bdi></td>)}</tr>)}</tbody></table></div>}<section className="space-y-3 rounded-lg border border-slate-200 bg-white p-4"><h2 className="font-semibold text-primary">{t("progress")}</h2>{progress.length ? progress.map((row, index) => <div key={String(row.agent_id ?? index)} className="flex items-center justify-between border-b border-slate-100 py-2 text-sm"><span className="text-primary"><bdi>{String(row.agent_code)}</bdi></span><span className="text-muted-foreground"><bdi>{String(row.completion_percent)}%</bdi> · <bdi>{String(row.complete_customers)}/{String(row.total_customers)}</bdi></span></div>) : <p className="text-muted-foreground">{t("noDashboardData")}</p>}</section></div>; }

export function LedgerView({ ageing, entries, customers, canRecordPayment }: { ageing: Row[]; entries: Row[]; customers: Row[]; canRecordPayment: boolean }) { const t = useTranslations("admin"); const [open, setOpen] = useState(false); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState(""); function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); startTransition(() => { void recordAdminLedgerPayment(new FormData(event.currentTarget)).then(() => { setMessage(t("saved")); setOpen(false); }).catch((error: unknown) => setMessage(error instanceof Error ? error.message : t("error"))); }); } return <div className="space-y-6"><PageHeader title={t("ledgerTitle")} description={t("ledgerDescription")} actions={canRecordPayment ? <Button type="button" onClick={() => setOpen((value) => !value)}>{t("recordPayment")}</Button> : undefined} />{open ? <form onSubmit={submit} className="grid gap-3 rounded-lg bg-slate-50 p-4 md:grid-cols-4"><label className="text-sm font-medium text-primary">{t("customer")}<select name="customerId" required className="mt-1 min-h-11 w-full rounded-md border border-slate-300 bg-white px-2"><option value="">—</option>{customers.map((customer) => <option key={String(customer.id)} value={String(customer.id)}>{String(customer.business_name)}</option>)}</select></label><label className="text-sm font-medium text-primary">{t("paymentAmount")}<input name="amountPKR" required inputMode="decimal" className="mt-1 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3" /></label><label className="text-sm font-medium text-primary">{t("reference")}<input name="reference" required className="mt-1 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3" /></label><label className="text-sm font-medium text-primary">{t("description")}<input name="description" required className="mt-1 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3" /></label><Button type="submit" disabled={pending}>{t("recordPayment")}</Button></form> : null}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{ageing.map((row) => <div key={String(row.bucket)} className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-sm text-muted-foreground"><bdi>{String(row.bucket)}</bdi></p><p className="mt-1 font-semibold text-primary"><bdi>PKR {String(row.balance_pkr)}</bdi></p><p className="text-sm text-muted-foreground"><bdi>{String(row.customer_count)}</bdi> {t("customerCount")}</p></div>)}</div><Table rows={entries} keys={["customer_id", "type", "amount_pkr", "reference_number", "entry_date", "description"]} />{entries.length === 0 ? <EmptyState title={t("noLedger")} description={t("noLedgerHint")} /> : null}{message ? <p role="status" className="text-sm font-medium text-primary">{message}</p> : null}</div>; }
