"use client";

import { useState } from "react";
import { useTranslations } from "next-intl";
import { approveRedemptionAction, adjustLoyaltyPointsAction, createRewardAction, rejectRedemptionAction } from "./actions";

type Reward = { id: string; name_en: string; name_ur: string; reward_type: string; points_cost: number; discount_value_pkr: string | null; discount_percent: string | null; stock_limit: number | null; redeemed_count: number; is_active: boolean };
type Redemption = { id: string; customer_id: string; points_spent: number; status: string; requested_at: string; customer?: { business_name?: string } | null; reward?: { name_en?: string; name_ur?: string } | null };
type Liability = { customers_with_points: number; total_points: number; value_per_point_pkr: string; estimated_liability_pkr: string } | null;
type Popularity = { reward_id: string; reward_name_en: string; reward_name_ur: string; request_count: number; approved_count: number };

export function RewardsAdminView({ rewards, redemptions, liability, popularity, canCreate, canApprove, canAdjust }: { rewards: Reward[]; redemptions: Redemption[]; liability: Liability; popularity: Popularity[]; canCreate: boolean; canApprove: boolean; canAdjust: boolean }) {
  const t = useTranslations("rewardAdmin");
  const [message, setMessage] = useState("");
  function notice(text: string) { setMessage(text); }
  return <div className="space-y-6">
    <header><h1 className="text-2xl font-bold text-primary">{t("title")}</h1><p className="text-muted-foreground">{t("description")}</p></header>
    {message ? <p role="status" className="rounded-md border border-slate-200 bg-white p-3 text-sm font-semibold text-primary">{message}</p> : null}
    {canCreate ? <section className="space-y-4 rounded-lg border border-slate-200 bg-white p-4"><h2 className="text-xl font-semibold text-primary">{t("createTitle")}</h2><form action={async (formData) => { try { await createRewardAction(formData); notice(t("created")); } catch { notice(t("createError")); } }} className="grid gap-3 md:grid-cols-2"><label className="space-y-1"><span>{t("nameEn")}</span><input required name="nameEn" className="min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="space-y-1"><span>{t("nameUr")}</span><input required name="nameUr" dir="rtl" className="font-urdu min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="space-y-1"><span>{t("descriptionEn")}</span><textarea name="descriptionEn" className="min-h-20 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="space-y-1"><span>{t("descriptionUr")}</span><textarea name="descriptionUr" dir="rtl" className="font-urdu min-h-20 w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="space-y-1"><span>{t("rewardType")}</span><select required name="rewardType" className="min-h-11 w-full rounded-md border border-slate-300 px-3"><option value="DISCOUNT_AMOUNT">{t("discountValue")}</option><option value="DISCOUNT_PERCENT">{t("discountPercent")}</option><option value="FREE_PRODUCT">{t("freeProductId")}</option><option value="GIFT">{t("gift")}</option></select></label><label className="space-y-1"><span>{t("pointsCost")}</span><input required min="1" type="number" name="pointsCost" className="min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="space-y-1"><span>{t("discountValue")}</span><input inputMode="decimal" name="discountValuePKR" className="min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="space-y-1"><span>{t("discountPercent")}</span><input inputMode="decimal" name="discountPercent" className="min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="space-y-1"><span>{t("freeProductId")}</span><input name="freeProductId" className="min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="space-y-1"><span>{t("freeProductQuantity")}</span><input inputMode="decimal" name="freeProductQuantity" className="min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="space-y-1"><span>{t("stockLimit")}</span><input type="number" name="stockLimit" className="min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><div className="md:col-span-2"><button type="submit" className="min-h-11 rounded-md bg-primary px-4 font-semibold text-white">{t("createReward")}</button></div></form></section> : null}
    <section className="space-y-3"><h2 className="text-xl font-semibold text-primary">{t("title")}</h2>{rewards.length === 0 ? <p className="rounded-lg border border-dashed border-slate-300 p-6 text-muted-foreground">{t("noRewards")}</p> : <div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="min-w-full text-start"><thead className="bg-slate-50"><tr><th className="p-3">{t("nameEn")}</th><th className="p-3">{t("rewardType")}</th><th className="p-3">{t("pointsCost")}</th><th className="p-3">{t("approvedCount")}</th></tr></thead><tbody>{rewards.map((reward) => <tr key={reward.id} className="border-t border-slate-100"><td className="p-3"><div>{reward.name_en}</div><div className="font-urdu" dir="rtl">{reward.name_ur}</div></td><td className="p-3"><bdi>{reward.reward_type}</bdi></td><td className="p-3"><bdi>{reward.points_cost}</bdi></td><td className="p-3"><bdi>{reward.redeemed_count}</bdi></td></tr>)}</tbody></table></div>}</section>
    <section className="grid gap-4 md:grid-cols-4"><article className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-sm text-muted-foreground">{t("customersWithPoints")}</p><p className="mt-2 text-2xl font-bold text-primary"><bdi>{liability?.customers_with_points ?? 0}</bdi></p></article><article className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-sm text-muted-foreground">{t("totalPoints")}</p><p className="mt-2 text-2xl font-bold text-primary"><bdi>{liability?.total_points ?? 0}</bdi></p></article><article className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-sm text-muted-foreground">{t("valuePerPoint")}</p><p className="mt-2 text-2xl font-bold text-primary"><bdi>PKR {liability?.value_per_point_pkr ?? "0.0000"}</bdi></p></article><article className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-sm text-muted-foreground">{t("estimatedLiability")}</p><p className="mt-2 text-2xl font-bold text-primary"><bdi>PKR {liability?.estimated_liability_pkr ?? "0.00"}</bdi></p></article></section>
    {canAdjust ? <section className="space-y-3 rounded-lg border border-slate-200 bg-white p-4"><h2 className="text-xl font-semibold text-primary">{t("adjustTitle")}</h2><form action={async (formData) => { try { await adjustLoyaltyPointsAction(formData); notice(t("adjusted")); } catch { notice(t("adjustmentError")); } }} className="grid gap-3 md:grid-cols-4"><input required name="customerId" placeholder={t("customerId")} className="min-h-11 rounded-md border border-slate-300 px-3" /><input required name="delta" type="number" placeholder={t("adjustment")} className="min-h-11 rounded-md border border-slate-300 px-3" /><input required name="reason" placeholder={t("adjustmentReason")} className="min-h-11 rounded-md border border-slate-300 px-3" /><button type="submit" className="min-h-11 rounded-md bg-primary px-4 font-semibold text-white">{t("adjustPoints")}</button></form></section> : null}
    <section className="space-y-3"><h2 className="text-xl font-semibold text-primary">{t("pendingTitle")}</h2>{redemptions.length === 0 ? <p className="rounded-lg border border-dashed border-slate-300 p-6 text-muted-foreground">{t("noPending")}</p> : <div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="min-w-full text-start"><thead className="bg-slate-50"><tr><th className="p-3">{t("customerId")}</th><th className="p-3">{t("rewardType")}</th><th className="p-3">{t("pointsCost")}</th><th className="p-3">{t("approve")}</th></tr></thead><tbody>{redemptions.map((item) => <tr key={item.id} className="border-t border-slate-100"><td className="p-3"><bdi>{item.customer?.business_name || item.customer_id}</bdi></td><td className="p-3">{item.reward?.name_en || t("notAvailable")}</td><td className="p-3"><bdi>{item.points_spent}</bdi></td><td className="p-3">{canApprove ? <><form action={async (formData) => { try { await approveRedemptionAction(formData); notice(t("approved")); } catch { notice(t("approvalError")); } }} className="flex min-w-[280px] gap-2"><input type="hidden" name="redemptionId" value={item.id} /><input name="orderId" placeholder={t("approveOrderId")} className="min-h-11 flex-1 rounded-md border border-slate-300 px-2" /><button type="submit" className="min-h-11 rounded-md bg-primary px-3 font-semibold text-white">{t("approve")}</button></form><form action={async (formData) => { try { await rejectRedemptionAction(formData); notice(t("rejected")); } catch { notice(t("rejectionError")); } }} className="mt-2 flex min-w-[280px] gap-2"><input type="hidden" name="redemptionId" value={item.id} /><input required name="reason" placeholder={t("rejectionReason")} className="min-h-11 flex-1 rounded-md border border-slate-300 px-2" /><button type="submit" className="min-h-11 rounded-md border border-primary px-3 font-semibold text-primary">{t("reject")}</button></form></> : null}</td></tr>)}</tbody></table></div>}</section>
    <section className="space-y-3"><h2 className="text-xl font-semibold text-primary">{t("popularityTitle")}</h2>{popularity.length === 0 ? <p className="rounded-lg border border-dashed border-slate-300 p-6 text-muted-foreground">{t("noRewards")}</p> : <div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="min-w-full text-start"><thead className="bg-slate-50"><tr><th className="p-3">{t("nameEn")}</th><th className="p-3">{t("requests")}</th><th className="p-3">{t("approvedCount")}</th></tr></thead><tbody>{popularity.map((item) => <tr key={item.reward_id} className="border-t border-slate-100"><td className="p-3"><div>{item.reward_name_en}</div><div className="font-urdu" dir="rtl">{item.reward_name_ur}</div></td><td className="p-3"><bdi>{item.request_count}</bdi></td><td className="p-3"><bdi>{item.approved_count}</bdi></td></tr>)}</tbody></table></div>}</section>
  </div>;
}
