"use client";

import { useMemo, useState } from "react";
import { useTranslations } from "next-intl";
import { createDeliveryRunAction, createPickingListAction, markPickingLineAction } from "./actions";

type Order = { id: string; order_number: string; status: string; total_pkr: string; payment_method: string; placed_at: string; customer?: { business_name?: string; area_code?: string } | null };
type Run = { id: string; run_number: string; driver_name: string; vehicle_number: string; run_date: string; status: string; total_stops: number; completed_stops: number; expected_cod_amount_pkr: string; collected_cod_amount_pkr: string };
type PickingLine = { id: string; quantity_required: string; quantity_picked: string; quantity_short: string; short_reason?: string | null; product?: { sku?: string; name_en?: string; name_ur?: string } | null };
type PickingList = { id: string; pick_number: string; status: string; picking_list_lines?: PickingLine[] };

export function DeliveryAdminView({ orders, runs, pickingLists }: { orders: Order[]; runs: Run[]; pickingLists: PickingList[] }) {
  const t = useTranslations("delivery");
  const [selectedOrders, setSelectedOrders] = useState<string[]>([]);
  const [codAmounts, setCodAmounts] = useState<Record<string, string>>({});
  const selectedOrderPayload = JSON.stringify(selectedOrders);
  const hasSelected = selectedOrders.length > 0;
  const selectedRunOrders = selectedOrders.filter((id) => orders.find((order) => order.id === id)?.status === "PICKED");
  const selectedRunOrderPayload = JSON.stringify(selectedRunOrders);
  const selectedRunCodPayload = JSON.stringify(Object.fromEntries(selectedRunOrders.map((id) => [id, codAmounts[id]]).filter(([, amount]) => amount)));
  const openOrders = useMemo(() => orders.filter((order) => order.status === "CONFIRMED" || order.status === "PICKED"), [orders]);
  const toggleOrder = (id: string) => setSelectedOrders((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const issueDriverLink = async (runId: string) => {
    const response = await fetch(`/api/admin/delivery/${runId}/driver-link`, { method: "POST" });
    const result = await response.json() as { url?: string; error?: string };
    if (!response.ok || !result.url) throw new Error(result.error ?? "The driver link could not be created.");
    await navigator.clipboard?.writeText(result.url);
    window.alert(result.url);
  };
  return <div className="space-y-8">
    <header><h1 className="text-2xl font-bold text-primary">{t("title")}</h1><p className="text-muted-foreground">{t("description")}</p></header>
    <section className="space-y-4 rounded-lg border border-slate-200 bg-white p-4"><h2 className="text-xl font-semibold text-primary">{t("selectOrders")}</h2>{openOrders.length === 0 ? <div className="rounded-md border border-dashed border-slate-300 p-6"><p className="font-semibold">{t("pickingEmpty")}</p><p className="text-muted-foreground">{t("pickingHint")}</p></div> : <div className="space-y-2">{openOrders.map((order) => <label key={order.id} className="flex min-h-11 items-center gap-3 rounded-md bg-slate-50 p-3"><input type="checkbox" checked={selectedOrders.includes(order.id)} onChange={() => toggleOrder(order.id)} className="h-5 w-5" /><span className="min-w-0 flex-1"><bdi>{order.order_number}</bdi> · {order.customer?.business_name ?? "—"} · {order.customer?.area_code ?? "—"}</span><span className="[unicode-bidi:isolate]"><bdi>PKR {order.total_pkr}</bdi></span>{order.payment_method !== "CREDIT" ? <input aria-label={t("codAmount")} value={codAmounts[order.id] ?? ""} onChange={(event) => setCodAmounts((current) => ({ ...current, [order.id]: event.target.value }))} placeholder={t("codAmount")} className="min-h-11 w-32 rounded-md border border-slate-300 bg-white px-2" /> : null}</label>)}</div>}
      <div className="flex flex-wrap gap-3"><form action={createPickingListAction}><input type="hidden" name="orderIdsJson" value={selectedOrderPayload} /><button disabled={!hasSelected} type="submit" className="min-h-11 rounded-md bg-primary px-4 font-semibold text-white disabled:opacity-50">{t("createPicking")}</button></form><p className="self-center text-sm text-muted-foreground">{t("assignedAgentNotified")}</p></div>
    </section>
    <section className="space-y-4"><h2 className="text-xl font-semibold text-primary">{t("picking")}</h2>{pickingLists.length === 0 ? <div className="rounded-md border border-dashed border-slate-300 p-6"><p className="font-semibold">{t("pickingEmpty")}</p><p className="text-muted-foreground">{t("pickingHint")}</p></div> : <div className="grid gap-4 md:grid-cols-2">{pickingLists.map((list) => <article key={list.id} className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><h3 className="font-semibold text-primary"><bdi>{list.pick_number}</bdi></h3><span className="text-sm text-muted-foreground">{list.status}</span></div><div className="mt-3 space-y-3">{(list.picking_list_lines ?? []).map((line) => <form key={line.id} action={markPickingLineAction} className="grid gap-2 rounded-md bg-slate-50 p-3 sm:grid-cols-[1fr_6rem_6rem_auto]"><input type="hidden" name="pickingListLineId" value={line.id} /><span className="self-center"><bdi>{line.product?.sku}</bdi> · {line.product?.name_en}</span><input name="quantityPicked" defaultValue={line.quantity_picked} aria-label={t("markPicked")} className="min-h-11 rounded-md border border-slate-300 bg-white px-2" /><input name="quantityShort" defaultValue={line.quantity_short} aria-label={t("shortageReason")} className="min-h-11 rounded-md border border-slate-300 bg-white px-2" /><button type="submit" className="min-h-11 rounded-md border border-primary px-3 font-semibold text-primary">{t("markPicked")}</button><input name="shortReason" defaultValue={line.short_reason ?? ""} placeholder={t("shortageReason")} className="min-h-11 rounded-md border border-slate-300 bg-white px-2 sm:col-span-4" /></form>)}</div></article>)}</div>}</section>
    <section className="space-y-4 rounded-lg border border-slate-200 bg-white p-4"><h2 className="text-xl font-semibold text-primary">{t("createRun")}</h2><p className="text-muted-foreground">{t("createRunHint")}</p><form action={createDeliveryRunAction} className="grid gap-3 md:grid-cols-2"><input type="hidden" name="orderIdsJson" value={selectedRunOrderPayload} /><input type="hidden" name="codAmountsJson" value={selectedRunCodPayload} /><label className="space-y-1"><span>{t("runDate")}</span><input required type="date" name="runDate" className="min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="space-y-1"><span>{t("driver")}</span><input required name="driverName" className="min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="space-y-1"><span>{t("vehicle")}</span><input required name="vehicleNumber" className="min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="space-y-1 md:col-span-2"><span>{t("notes")}</span><textarea name="notes" className="min-h-20 w-full rounded-md border border-slate-300 px-3 py-2" /></label><button disabled={selectedRunOrders.length === 0} type="submit" className="min-h-11 rounded-md bg-primary px-4 font-semibold text-white disabled:opacity-50 md:w-fit">{t("createRun")}</button></form></section>
    <section className="space-y-4"><h2 className="text-xl font-semibold text-primary">{t("runs")}</h2>{runs.length === 0 ? <div className="rounded-md border border-dashed border-slate-300 p-6"><p className="font-semibold">{t("noRuns")}</p><p className="text-muted-foreground">{t("noRunsHint")}</p></div> : <div className="grid gap-4 md:grid-cols-2">{runs.map((run) => <article key={run.id} className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><h3 className="font-semibold text-primary"><bdi>{run.run_number}</bdi></h3><span>{run.status}</span></div><p className="mt-2">{run.driver_name} · <bdi>{run.vehicle_number}</bdi></p><p className="mt-2 text-sm text-muted-foreground"><bdi>{run.completed_stops}/{run.total_stops}</bdi> {t("completedStops")} · <bdi>PKR {run.collected_cod_amount_pkr}/{run.expected_cod_amount_pkr}</bdi> {t("collectedCod")}</p><button type="button" onClick={() => void issueDriverLink(run.id)} className="mt-3 min-h-11 rounded-md border border-primary px-3 font-semibold text-primary">{t("tokenLink")}</button></article>)}</div>}</section>
  </div>;
}
