import json
from pathlib import Path
additions = {
  "en.json": {
    "captureLocation": "Capture location",
    "locationCaptured": "Location captured. Review it before saving.",
    "locationError": "GPS could not be captured. You can still save the visit without location.",
    "locationHint": "Only captured after you tap the button.",
    "locationSaveWithout": "If GPS fails, save the Visit without location. It will not block logging.",
    "route": "Route",
    "routeTitle": "Customer route",
    "routeDescription": "See your customers by recent order activity and find customers near you.",
    "customersNearMe": "Customers near me",
    "findNearby": "Find customers near me",
    "nearbyHint": "Location is used only for this action and is not tracked in the background.",
    "noNearby": "No nearby customers found.",
    "noNearbyHint": "Try again from a different location or check customer coordinates.",
    "distance": "Distance",
    "calendar": "Calendar",
    "calendarTitle": "Sales calendar",
    "calendarDescription": "Subscribe to your follow-ups in Google, Outlook, or Apple Calendar.",
    "createCalendarFeed": "Create calendar feed",
    "calendarFeedReady": "Your calendar feed is ready. Keep this private.",
    "calendarFeedHint": "If you create a new feed, the previous link will remain private but cannot be recovered here.",
    "performance": "Performance",
    "performanceTitle": "My performance",
    "performanceDescription": "This month's orders, revenue, quote conversion, and target progress.",
    "quoteConversion": "Quote conversion",
    "targetProgress": "Target progress",
    "monthlyTarget": "Monthly target",
    "dailyRevenue": "Daily revenue",
    "noRevenue": "No daily revenue yet.",
    "noRevenueHint": "Placed orders will appear here by Karachi business date.",
    "placeForCustomer": "Place order for customer",
    "chooseCustomerFirst": "Choose a customer first",
    "customerPickerHint": "The catalogue will use this customer's exact Vendor visibility.",
    "visibleProducts": "Visible products",
    "quantity": "Quantity",
    "addProduct": "Add product",
    "placeOrder": "Place order",
    "orderPlaced": "Order placed for customer.",
    "noVisibleProducts": "No visible products for this customer.",
    "noVisibleProductsHint": "Ask an administrator to review this customer's catalogue visibility.",
    "orderOnBehalfError": "The order could not be placed. Review customer visibility and quantities.",
  },
  "ur.json": {
    "captureLocation": "Location capture کریں",
    "locationCaptured": "Location capture ہو گئی۔ Save کرنے سے پہلے review کریں۔",
    "locationError": "GPS capture نہیں ہو سکی۔ Visit location کے بغیر بھی save ہو سکتی ہے۔",
    "locationHint": "صرف button دبانے کے بعد capture ہو گی۔",
    "locationSaveWithout": "GPS fail ہو تو Visit location کے بغیر save کریں۔ Logging نہیں رکے گی۔",
    "route": "Route",
    "routeTitle": "Customer route",
    "routeDescription": "Recent order activity کے مطابق customers دیکھیں اور اپنے قریب customers تلاش کریں۔",
    "customersNearMe": "میرے قریب customers",
    "findNearby": "میرے قریب customers تلاش کریں",
    "nearbyHint": "Location صرف اس action کے لیے استعمال ہو گی؛ background tracking نہیں ہو گی۔",
    "noNearby": "قریب کوئی customer نہیں ملا۔",
    "noNearbyHint": "دوسری جگہ سے دوبارہ کوشش کریں یا customer coordinates چیک کریں۔",
    "distance": "فاصلہ",
    "calendar": "Calendar",
    "calendarTitle": "Sales calendar",
    "calendarDescription": "اپنے follow-ups کو Google، Outlook یا Apple Calendar میں subscribe کریں۔",
    "createCalendarFeed": "Calendar feed بنائیں",
    "calendarFeedReady": "Calendar feed تیار ہے۔ اسے private رکھیں۔",
    "calendarFeedHint": "نیا feed بنانے پر پچھلا link private رہے گا مگر یہاں recover نہیں ہو سکے گا۔",
    "performance": "Performance",
    "performanceTitle": "میری performance",
    "performanceDescription": "اس ماہ کے orders، revenue، quote conversion اور target progress۔",
    "quoteConversion": "Quote conversion",
    "targetProgress": "Target progress",
    "monthlyTarget": "Monthly target",
    "dailyRevenue": "Daily revenue",
    "noRevenue": "ابھی daily revenue نہیں۔",
    "noRevenueHint": "Placed orders Karachi business date کے مطابق یہاں آئیں گے۔",
    "placeForCustomer": "Customer کے لیے order place کریں",
    "chooseCustomerFirst": "پہلے customer منتخب کریں",
    "customerPickerHint": "Catalogue اسی customer کی Vendor visibility استعمال کرے گا۔",
    "visibleProducts": "Visible products",
    "quantity": "Quantity",
    "addProduct": "Product شامل کریں",
    "placeOrder": "Order place کریں",
    "orderPlaced": "Customer کے لیے order place ہو گیا۔",
    "noVisibleProducts": "اس customer کے لیے کوئی visible product نہیں۔",
    "noVisibleProductsHint": "Administrator سے customer کی catalogue visibility review کرنے کو کہیں۔",
    "orderOnBehalfError": "Order place نہیں ہو سکا۔ Customer visibility اور quantities review کریں۔",
  }
}
for filename, values in additions.items():
    path = Path("messages") / filename
    data = json.loads(path.read_text())
    data["sales"].update(values)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
